name: Nix Flake Integration

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  flake-check:
    name: "[check] nix flake"
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true
    - uses: cachix/install-nix-action@v18
    - uses: cachix/cachix-action@v12
      with:
        name: polkadot-tests
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Run nix integration check
      run: nix flake check ".?submodules=1"
