name: Nix Flake Integration

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        package: 
        - gossamer-adapter
        - kagome-adapter
        - substrate-adapter
        - gossamer-host
        - kagome-host
        - substrate-host
        - hostapi-runtime
        - tester-runtime
    name: "[build] ${{ matrix.package }}"
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0
    - uses: cachix/install-nix-action@v20
    - uses: cachix/cachix-action@v12
      with:
        name: polkadot-tests
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build ${{ matrix.package }}
      run: |
        nix flake lock --update-input substrate-submodule --update-input kagome-submodule --update-input gossamer-submodule
        nix build .#${{ matrix.package }}

  check:
    needs: [ build ]
    name: "[test] flake check"
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0
    - uses: cachix/install-nix-action@v20
    - uses: cachix/cachix-action@v12
      with:
        name: polkadot-tests
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Run flake check
      run: |
        nix flake lock --update-input substrate-submodule --update-input kagome-submodule --update-input gossamer-submodule
        nix flake check
